version: "3.6"
services:
  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/:/etc/nginx/templates/"
      - ./:/var/www/html:rw,cached
      - ./docker/certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    restart: always

  mysql:
    image: mariadb
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    command: --lower_case_table_names=2
    volumes:
      - db_data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-wordpress
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  composer:
    image: composer:1.10
    container_name: ${COMPOSE_PROJECT_NAME}-composer
    working_dir: /var/www/html
    restart: "no"
    volumes:
      - ./:/var/www/html:rw,cached

volumes:
  db_data:
